<?
$core['events']['on_off'] = "1";
$eventtime['1']['name']             = "Blood Castle";
$eventtime['1']['repeattime']     = "500";
$eventtime['1']['opentime']          = "300";
$eventtime['2']['name']             = "Devil Square";
$eventtime['2']['repeattime']     = "7200";
$eventtime['2']['opentime']          = "300";
$eventtime['3']['name']             = "Chaos Castle";
$eventtime['3']['repeattime']     = "7200";
$eventtime['3']['opentime']          = "300";
$eventtime['4']['name']             = "White Wizard Invasion";
$eventtime['4']['repeattime']     = "7200";
$eventtime['4']['opentime']          = "300";
$eventtime['5']['name']             = "Golden Invasion";
$eventtime['5']['repeattime']     = "7200";
$eventtime['5']['opentime']          = "300";
$eventtime['6']['name']             = "Crywolf Fotress";
$eventtime['6']['repeattime']     = "7200";
$eventtime['6']['opentime']          = "300";
$eventtime['7']['name']             = "Castle Siege";
$eventtime['7']['repeattime']     = "7200";
$eventtime['7']['opentime']          = "300";
$eventtime['8']['name']             = "Kanturu Event";
$eventtime['8']['repeattime']     = "7200";
$eventtime['8']['opentime']          = "300";
$eventtime['9']['name']             = "Illusion Temple";
$eventtime['9']['repeattime']     = "7200";
$eventtime['9']['opentime']          = "300";
$eventtime['10']['name']         = "Cherry Blossom";
$eventtime['10']['repeattime']     = "7200";
$eventtime['10']['opentime']     = "300";
$eventtime['11']['name']         = "Raklion Hatchery";
$eventtime['11']['repeattime']     = "7200";
$eventtime['11']['opentime']     = "300";
$eventtime['12']['name']         = "NPC Merchant Moss";
$eventtime['12']['repeattime']     = "7200";
$eventtime['12']['opentime']     = "300";
$eventtime['13']['name']         = "Doublegoer";
$eventtime['13']['repeattime']     = "7200";
$eventtime['13']['opentime']     = "300";
$eventtime['14']['name']         = "Fortress of Imperial Guardian";
$eventtime['14']['repeattime']     = "7200";
$eventtime['14']['opentime']     = "300";

define('WEBSITE_REAL_TIME', time());
?>